from typing import Protocol, List, Dict, Any, Optional, Tuple

class Retriever(Protocol):
    def search(self, query_string: str, *, lexical_limit: int, minilm_k: int, sapbert_k: int,
               target_ontologies: Optional[List[str]] = None) -> Dict[str, Any]: ...
    def get_term_details(self, term_id: str) -> Optional[Dict[str, Any]]: ...

class LLMClient(Protocol):
    async def generate_json(self, prompt: str, *, model: str, json_schema: Optional[Dict] = None) -> Tuple[Optional[str], Optional[Dict[str, int]]]: ...
